#!/bin/bash
# Code generated by protoc-gen-liquibase. DO NOT EDIT.

# Command Arguments
AUTHOR=${1}
CHANGELOGFILE=${2}
CONTEXTFILTER=${3}
DEFAULTCATALOGNAME=${4}
DEFAULTSCHEMANAME=${5}
DIFFTYPES=${6}
DRIFTSEVERITY=${7}
DRIFTSEVERITYCHANGED=${8}
DRIFTSEVERITYMISSING=${9}
DRIFTSEVERITYUNEXPECTED=${10}
DRIVER=${11}
DRIVERPROPERTIESFILE=${12}
EXCLUDEOBJECTS=${13}
INCLUDECATALOG=${14}
INCLUDEOBJECTS=${15}
INCLUDESCHEMA=${16}
INCLUDETABLESPACE=${17}
LABELFILTER=${18}
OUTPUTSCHEMAS=${19}
PASSWORD=${20}
REFERENCEDEFAULTCATALOGNAME=${21}
REFERENCEDEFAULTSCHEMANAME=${22}
REFERENCEDRIVER=${23}
REFERENCEDRIVERPROPERTIESFILE=${24}
REFERENCELIQUIBASECATALOGNAME=${25}
REFERENCELIQUIBASESCHEMANAME=${26}
REFERENCEPASSWORD=${27}
REFERENCESCHEMAS=${28}
REFERENCEURL=${29}
REFERENCEUSERNAME=${30}
REPLACEIFEXISTSTYPES=${31}
REPORTENABLED=${32}
REPORTNAME=${33}
REPORTPATH=${34}
RUNONCHANGETYPES=${35}
SCHEMAS=${36}
URL=${37}
USEORREPLACEOPTION=${38}
USERNAME=${39}
# Global Options
ADDEMPTYMDCVALUES=${40}
ALLOWDUPLICATEDCHANGESETIDENTIFIERS=${41}
ALWAYSDROPINSTEADOFREPLACE=${42}
ALWAYSOVERRIDESTOREDLOGICSCHEMA=${43}
AUTOREORG=${44}
CHANGELOGLOCKPOLLRATE=${45}
CHANGELOGLOCKWAITTIMEINMINUTES=${46}
CHANGELOGPARSEMODE=${47}
CLASSPATH=${48}
CONVERTDATATYPES=${49}
CUSTOMLOGDATAFILE=${50}
CUSTOMLOGDATAFREQUENCY=${51}
DATABASECHANGELOGLOCKTABLENAME=${52}
DATABASECHANGELOGTABLENAME=${53}
DATABASECLASS=${54}
DDLLOCKTIMEOUT=${55}
DEFAULTSFILE=${56}
DIFFCOLUMNORDER=${57}
DUPLICATEFILEMODE=${58}
ERRORONCIRCULARINCLUDEALL=${59}
FILEENCODING=${60}
FILTERLOGMESSAGES=${61}
FLOWVERBOSETOSTRING=${62}
GENERATECHANGESETCREATEDVALUES=${63}
GENERATEDCHANGESETIDSCONTAINSDESCRIPTION=${64}
HEADLESS=${65}
INCLUDECATALOGINSPECIFICATION=${66}
INCLUDEMATCHINGTAGINROLLBACKOLDEST=${67}
INCLUDERELATIONSFORCOMPUTEDCOLUMNS=${68}
INCLUDESYSTEMCLASSPATH=${69}
LICENSEKEY=${70}
LIQUIBASECATALOGNAME=${71}
LIQUIBASESCHEMANAME=${72}
LIQUIBASETABLESPACENAME=${73}
LOGCHANNELS=${74}
LOGFILE=${75}
LOGFORMAT=${76}
LOGLEVEL=${77}
MIRRORCONSOLEMESSAGESTOLOG=${78}
MISSINGPROPERTYMODE=${79}
MONITORPERFORMANCE=${80}
NATIVEEXECUTOR=${81}
ONMISSINGINCLUDECHANGELOG=${82}
ONMISSINGSQLFILE=${83}
OUTPUTFILE=${84}
OUTPUTFILEENCODING=${85}
OUTPUTLINESEPARATOR=${86}
PRESERVESCHEMACASE=${87}
PROFORCEONPARTIALCHANGES=${88}
PROGLOBALENDDELIMITER=${89}
PROGLOBALENDDELIMITERPRIORITIZED=${90}
PROLICENSEKEY=${91}
PROMARKUNUSEDNOTDROP=${92}
PROSQLINLINE=${93}
PROSYNONYMSDROPPUBLIC=${94}
PROMPTFORNONLOCALDATABASE=${95}
PROPERTYPROVIDERCLASS=${96}
REPORTSENABLED=${97}
REPORTSFORMAT=${98}
REPORTSNAME=${99}
REPORTSPATH=${100}
SEARCHPATH=${101}
SECUREPARSING=${102}
SHOULDGENERATEROLLBACKREPORT=${103}
SHOULDRUN=${104}
SHOULDSNAPSHOTDATA=${105}
SHOWBANNER=${106}
SHOWHIDDENARGS=${107}
SQLLOGLEVEL=${108}
SQLSHOWSQLWARNINGS=${109}
STRICT=${110}
SUPPORTPROPERTYESCAPING=${111}
UISERVICE=${112}
USEPROCEDURESCHEMA=${113}
VALIDATEXMLCHANGELOGFILES=${114}

if [[ -z "$CHANGELOGFILE" ]]; then
	echo "changelogFile is required"
	exit 1
fi
if [[ -z "$REFERENCEURL" ]]; then
	echo "referenceUrl is required"
	exit 1
fi
if [[ -z "$URL" ]]; then
	echo "url is required"
	exit 1
fi

PARAMS=()

if [[ -n "$AUTHOR" ]]; then
	PARAMS+=("--author=$AUTHOR")
fi
if [[ -n "$CHANGELOGFILE" ]]; then
	PARAMS+=("--changelog-file=$CHANGELOGFILE")
fi
if [[ -n "$CONTEXTFILTER" ]]; then
	PARAMS+=("--context-filter=$CONTEXTFILTER")
fi
if [[ -n "$DEFAULTCATALOGNAME" ]]; then
	PARAMS+=("--default-catalog-name=$DEFAULTCATALOGNAME")
fi
if [[ -n "$DEFAULTSCHEMANAME" ]]; then
	PARAMS+=("--default-schema-name=$DEFAULTSCHEMANAME")
fi
if [[ -n "$DIFFTYPES" ]]; then
	PARAMS+=("--diff-types=$DIFFTYPES")
fi
if [[ -n "$DRIFTSEVERITY" ]]; then
	PARAMS+=("--drift-severity=$DRIFTSEVERITY")
fi
if [[ -n "$DRIFTSEVERITYCHANGED" ]]; then
	PARAMS+=("--drift-severity-changed=$DRIFTSEVERITYCHANGED")
fi
if [[ -n "$DRIFTSEVERITYMISSING" ]]; then
	PARAMS+=("--drift-severity-missing=$DRIFTSEVERITYMISSING")
fi
if [[ -n "$DRIFTSEVERITYUNEXPECTED" ]]; then
	PARAMS+=("--drift-severity-unexpected=$DRIFTSEVERITYUNEXPECTED")
fi
if [[ -n "$DRIVER" ]]; then
	PARAMS+=("--driver=$DRIVER")
fi
if [[ -n "$DRIVERPROPERTIESFILE" ]]; then
	PARAMS+=("--driver-properties-file=$DRIVERPROPERTIESFILE")
fi
if [[ -n "$EXCLUDEOBJECTS" ]]; then
	PARAMS+=("--exclude-objects=$EXCLUDEOBJECTS")
fi
if [[ -n "$INCLUDECATALOG" ]]; then
	PARAMS+=("--include-catalog=$INCLUDECATALOG")
fi
if [[ -n "$INCLUDEOBJECTS" ]]; then
	PARAMS+=("--include-objects=$INCLUDEOBJECTS")
fi
if [[ -n "$INCLUDESCHEMA" ]]; then
	PARAMS+=("--include-schema=$INCLUDESCHEMA")
fi
if [[ -n "$INCLUDETABLESPACE" ]]; then
	PARAMS+=("--include-tablespace=$INCLUDETABLESPACE")
fi
if [[ -n "$LABELFILTER" ]]; then
	PARAMS+=("--label-filter=$LABELFILTER")
fi
if [[ -n "$OUTPUTSCHEMAS" ]]; then
	PARAMS+=("--output-schemas=$OUTPUTSCHEMAS")
fi
if [[ -n "$PASSWORD" ]]; then
	PARAMS+=("--password=$PASSWORD")
fi
if [[ -n "$REFERENCEDEFAULTCATALOGNAME" ]]; then
	PARAMS+=("--reference-default-catalog-name=$REFERENCEDEFAULTCATALOGNAME")
fi
if [[ -n "$REFERENCEDEFAULTSCHEMANAME" ]]; then
	PARAMS+=("--reference-default-schema-name=$REFERENCEDEFAULTSCHEMANAME")
fi
if [[ -n "$REFERENCEDRIVER" ]]; then
	PARAMS+=("--reference-driver=$REFERENCEDRIVER")
fi
if [[ -n "$REFERENCEDRIVERPROPERTIESFILE" ]]; then
	PARAMS+=("--reference-driver-properties-file=$REFERENCEDRIVERPROPERTIESFILE")
fi
if [[ -n "$REFERENCELIQUIBASECATALOGNAME" ]]; then
	PARAMS+=("--reference-liquibase-catalog-name=$REFERENCELIQUIBASECATALOGNAME")
fi
if [[ -n "$REFERENCELIQUIBASESCHEMANAME" ]]; then
	PARAMS+=("--reference-liquibase-schema-name=$REFERENCELIQUIBASESCHEMANAME")
fi
if [[ -n "$REFERENCEPASSWORD" ]]; then
	PARAMS+=("--reference-password=$REFERENCEPASSWORD")
fi
if [[ -n "$REFERENCESCHEMAS" ]]; then
	PARAMS+=("--reference-schemas=$REFERENCESCHEMAS")
fi
if [[ -n "$REFERENCEURL" ]]; then
	PARAMS+=("--reference-url=$REFERENCEURL")
fi
if [[ -n "$REFERENCEUSERNAME" ]]; then
	PARAMS+=("--reference-username=$REFERENCEUSERNAME")
fi
if [[ -n "$REPLACEIFEXISTSTYPES" ]]; then
	PARAMS+=("--replace-if-exists-types=$REPLACEIFEXISTSTYPES")
fi
if [[ -n "$REPORTENABLED" ]]; then
	PARAMS+=("--report-enabled=$REPORTENABLED")
fi
if [[ -n "$REPORTNAME" ]]; then
	PARAMS+=("--report-name=$REPORTNAME")
fi
if [[ -n "$REPORTPATH" ]]; then
	PARAMS+=("--report-path=$REPORTPATH")
fi
if [[ -n "$RUNONCHANGETYPES" ]]; then
	PARAMS+=("--run-on-change-types=$RUNONCHANGETYPES")
fi
if [[ -n "$SCHEMAS" ]]; then
	PARAMS+=("--schemas=$SCHEMAS")
fi
if [[ -n "$URL" ]]; then
	PARAMS+=("--url=$URL")
fi
if [[ -n "$USEORREPLACEOPTION" ]]; then
	PARAMS+=("--use-or-replace-option=$USEORREPLACEOPTION")
fi
if [[ -n "$USERNAME" ]]; then
	PARAMS+=("--username=$USERNAME")
fi

GLOBALS=()

if [[ -n "$ADDEMPTYMDCVALUES" ]]; then
	GLOBALS+=("--add-empty-mdc-values=$ADDEMPTYMDCVALUES")
fi
if [[ -n "$ALLOWDUPLICATEDCHANGESETIDENTIFIERS" ]]; then
	GLOBALS+=("--allow-duplicated-changeset-identifiers=$ALLOWDUPLICATEDCHANGESETIDENTIFIERS")
fi
if [[ -n "$ALWAYSDROPINSTEADOFREPLACE" ]]; then
	GLOBALS+=("--always-drop-instead-of-replace=$ALWAYSDROPINSTEADOFREPLACE")
fi
if [[ -n "$ALWAYSOVERRIDESTOREDLOGICSCHEMA" ]]; then
	GLOBALS+=("--always-override-stored-logic-schema=$ALWAYSOVERRIDESTOREDLOGICSCHEMA")
fi
if [[ -n "$AUTOREORG" ]]; then
	GLOBALS+=("--auto-reorg=$AUTOREORG")
fi
if [[ -n "$CHANGELOGLOCKPOLLRATE" ]]; then
	GLOBALS+=("--changelog-lock-poll-rate=$CHANGELOGLOCKPOLLRATE")
fi
if [[ -n "$CHANGELOGLOCKWAITTIMEINMINUTES" ]]; then
	GLOBALS+=("--changelog-lock-wait-time-in-minutes=$CHANGELOGLOCKWAITTIMEINMINUTES")
fi
if [[ -n "$CHANGELOGPARSEMODE" ]]; then
	GLOBALS+=("--changelog-parse-mode=$CHANGELOGPARSEMODE")
fi
if [[ -n "$CLASSPATH" ]]; then
	GLOBALS+=("--classpath=$CLASSPATH")
fi
if [[ -n "$CONVERTDATATYPES" ]]; then
	GLOBALS+=("--convert-data-types=$CONVERTDATATYPES")
fi
if [[ -n "$CUSTOMLOGDATAFILE" ]]; then
	GLOBALS+=("--custom-log-data-file=$CUSTOMLOGDATAFILE")
fi
if [[ -n "$CUSTOMLOGDATAFREQUENCY" ]]; then
	GLOBALS+=("--custom-log-data-frequency=$CUSTOMLOGDATAFREQUENCY")
fi
if [[ -n "$DATABASECHANGELOGLOCKTABLENAME" ]]; then
	GLOBALS+=("--database-changelog-lock-table-name=$DATABASECHANGELOGLOCKTABLENAME")
fi
if [[ -n "$DATABASECHANGELOGTABLENAME" ]]; then
	GLOBALS+=("--database-changelog-table-name=$DATABASECHANGELOGTABLENAME")
fi
if [[ -n "$DATABASECLASS" ]]; then
	GLOBALS+=("--database-class=$DATABASECLASS")
fi
if [[ -n "$DDLLOCKTIMEOUT" ]]; then
	GLOBALS+=("--ddl-lock-timeout=$DDLLOCKTIMEOUT")
fi
if [[ -n "$DEFAULTSFILE" ]]; then
	GLOBALS+=("--defaults-file=$DEFAULTSFILE")
fi
if [[ -n "$DIFFCOLUMNORDER" ]]; then
	GLOBALS+=("--diff-column-order=$DIFFCOLUMNORDER")
fi
if [[ -n "$DUPLICATEFILEMODE" ]]; then
	GLOBALS+=("--duplicate-file-mode=$DUPLICATEFILEMODE")
fi
if [[ -n "$ERRORONCIRCULARINCLUDEALL" ]]; then
	GLOBALS+=("--error-on-circular-include-all=$ERRORONCIRCULARINCLUDEALL")
fi
if [[ -n "$FILEENCODING" ]]; then
	GLOBALS+=("--file-encoding=$FILEENCODING")
fi
if [[ -n "$FILTERLOGMESSAGES" ]]; then
	GLOBALS+=("--filter-log-messages=$FILTERLOGMESSAGES")
fi
if [[ -n "$FLOWVERBOSETOSTRING" ]]; then
	GLOBALS+=("--flow-verbose-to-string=$FLOWVERBOSETOSTRING")
fi
if [[ -n "$GENERATECHANGESETCREATEDVALUES" ]]; then
	GLOBALS+=("--generate-changeset-created-values=$GENERATECHANGESETCREATEDVALUES")
fi
if [[ -n "$GENERATEDCHANGESETIDSCONTAINSDESCRIPTION" ]]; then
	GLOBALS+=("--generated-changeset-ids-contains-description=$GENERATEDCHANGESETIDSCONTAINSDESCRIPTION")
fi
if [[ -n "$HEADLESS" ]]; then
	GLOBALS+=("--headless=$HEADLESS")
fi
if [[ -n "$INCLUDECATALOGINSPECIFICATION" ]]; then
	GLOBALS+=("--include-catalog-in-specification=$INCLUDECATALOGINSPECIFICATION")
fi
if [[ -n "$INCLUDEMATCHINGTAGINROLLBACKOLDEST" ]]; then
	GLOBALS+=("--include-matching-tag-in-rollback-oldest=$INCLUDEMATCHINGTAGINROLLBACKOLDEST")
fi
if [[ -n "$INCLUDERELATIONSFORCOMPUTEDCOLUMNS" ]]; then
	GLOBALS+=("--include-relations-for-computed-columns=$INCLUDERELATIONSFORCOMPUTEDCOLUMNS")
fi
if [[ -n "$INCLUDESYSTEMCLASSPATH" ]]; then
	GLOBALS+=("--include-system-classpath=$INCLUDESYSTEMCLASSPATH")
fi
if [[ -n "$LICENSEKEY" ]]; then
	GLOBALS+=("--license-key=$LICENSEKEY")
fi
if [[ -n "$LIQUIBASECATALOGNAME" ]]; then
	GLOBALS+=("--liquibase-catalog-name=$LIQUIBASECATALOGNAME")
fi
if [[ -n "$LIQUIBASESCHEMANAME" ]]; then
	GLOBALS+=("--liquibase-schema-name=$LIQUIBASESCHEMANAME")
fi
if [[ -n "$LIQUIBASETABLESPACENAME" ]]; then
	GLOBALS+=("--liquibase-tablespace-name=$LIQUIBASETABLESPACENAME")
fi
if [[ -n "$LOGCHANNELS" ]]; then
	GLOBALS+=("--log-channels=$LOGCHANNELS")
fi
if [[ -n "$LOGFILE" ]]; then
	GLOBALS+=("--log-file=$LOGFILE")
fi
if [[ -n "$LOGFORMAT" ]]; then
	GLOBALS+=("--log-format=$LOGFORMAT")
fi
if [[ -n "$LOGLEVEL" ]]; then
	GLOBALS+=("--log-level=$LOGLEVEL")
fi
if [[ -n "$MIRRORCONSOLEMESSAGESTOLOG" ]]; then
	GLOBALS+=("--mirror-console-messages-to-log=$MIRRORCONSOLEMESSAGESTOLOG")
fi
if [[ -n "$MISSINGPROPERTYMODE" ]]; then
	GLOBALS+=("--missing-property-mode=$MISSINGPROPERTYMODE")
fi
if [[ -n "$MONITORPERFORMANCE" ]]; then
	GLOBALS+=("--monitor-performance=$MONITORPERFORMANCE")
fi
if [[ -n "$NATIVEEXECUTOR" ]]; then
	GLOBALS+=("--native-executor=$NATIVEEXECUTOR")
fi
if [[ -n "$ONMISSINGINCLUDECHANGELOG" ]]; then
	GLOBALS+=("--on-missing-include-changelog=$ONMISSINGINCLUDECHANGELOG")
fi
if [[ -n "$ONMISSINGSQLFILE" ]]; then
	GLOBALS+=("--on-missing-sql-file=$ONMISSINGSQLFILE")
fi
if [[ -n "$OUTPUTFILE" ]]; then
	GLOBALS+=("--output-file=$OUTPUTFILE")
fi
if [[ -n "$OUTPUTFILEENCODING" ]]; then
	GLOBALS+=("--output-file-encoding=$OUTPUTFILEENCODING")
fi
if [[ -n "$OUTPUTLINESEPARATOR" ]]; then
	GLOBALS+=("--output-line-separator=$OUTPUTLINESEPARATOR")
fi
if [[ -n "$PRESERVESCHEMACASE" ]]; then
	GLOBALS+=("--preserve-schema-case=$PRESERVESCHEMACASE")
fi
if [[ -n "$PROFORCEONPARTIALCHANGES" ]]; then
	GLOBALS+=("--pro-force-on-partial-changes=$PROFORCEONPARTIALCHANGES")
fi
if [[ -n "$PROGLOBALENDDELIMITER" ]]; then
	GLOBALS+=("--pro-global-end-delimiter=$PROGLOBALENDDELIMITER")
fi
if [[ -n "$PROGLOBALENDDELIMITERPRIORITIZED" ]]; then
	GLOBALS+=("--pro-global-end-delimiter-prioritized=$PROGLOBALENDDELIMITERPRIORITIZED")
fi
if [[ -n "$PROLICENSEKEY" ]]; then
	GLOBALS+=("--pro-license-key=$PROLICENSEKEY")
fi
if [[ -n "$PROMARKUNUSEDNOTDROP" ]]; then
	GLOBALS+=("--pro-mark-unused-not-drop=$PROMARKUNUSEDNOTDROP")
fi
if [[ -n "$PROSQLINLINE" ]]; then
	GLOBALS+=("--pro-sql-inline=$PROSQLINLINE")
fi
if [[ -n "$PROSYNONYMSDROPPUBLIC" ]]; then
	GLOBALS+=("--pro-synonyms-drop-public=$PROSYNONYMSDROPPUBLIC")
fi
if [[ -n "$PROMPTFORNONLOCALDATABASE" ]]; then
	GLOBALS+=("--prompt-for-non-local-database=$PROMPTFORNONLOCALDATABASE")
fi
if [[ -n "$PROPERTYPROVIDERCLASS" ]]; then
	GLOBALS+=("--property-provider-class=$PROPERTYPROVIDERCLASS")
fi
if [[ -n "$REPORTSENABLED" ]]; then
	GLOBALS+=("--reports-enabled=$REPORTSENABLED")
fi
if [[ -n "$REPORTSFORMAT" ]]; then
	GLOBALS+=("--reports-format=$REPORTSFORMAT")
fi
if [[ -n "$REPORTSNAME" ]]; then
	GLOBALS+=("--reports-name=$REPORTSNAME")
fi
if [[ -n "$REPORTSPATH" ]]; then
	GLOBALS+=("--reports-path=$REPORTSPATH")
fi
if [[ -n "$SEARCHPATH" ]]; then
	GLOBALS+=("--search-path=$SEARCHPATH")
fi
if [[ -n "$SECUREPARSING" ]]; then
	GLOBALS+=("--secure-parsing=$SECUREPARSING")
fi
if [[ -n "$SHOULDGENERATEROLLBACKREPORT" ]]; then
	GLOBALS+=("--should-generate-rollback-report=$SHOULDGENERATEROLLBACKREPORT")
fi
if [[ -n "$SHOULDRUN" ]]; then
	GLOBALS+=("--should-run=$SHOULDRUN")
fi
if [[ -n "$SHOULDSNAPSHOTDATA" ]]; then
	GLOBALS+=("--should-snapshot-data=$SHOULDSNAPSHOTDATA")
fi
if [[ -n "$SHOWBANNER" ]]; then
	GLOBALS+=("--show-banner=$SHOWBANNER")
fi
if [[ -n "$SHOWHIDDENARGS" ]]; then
	GLOBALS+=("--show-hidden-args=$SHOWHIDDENARGS")
fi
if [[ -n "$SQLLOGLEVEL" ]]; then
	GLOBALS+=("--sql-log-level=$SQLLOGLEVEL")
fi
if [[ -n "$SQLSHOWSQLWARNINGS" ]]; then
	GLOBALS+=("--sql-show-sql-warnings=$SQLSHOWSQLWARNINGS")
fi
if [[ -n "$STRICT" ]]; then
	GLOBALS+=("--strict=$STRICT")
fi
if [[ -n "$SUPPORTPROPERTYESCAPING" ]]; then
	GLOBALS+=("--support-property-escaping=$SUPPORTPROPERTYESCAPING")
fi
if [[ -n "$UISERVICE" ]]; then
	GLOBALS+=("--ui-service=$UISERVICE")
fi
if [[ -n "$USEPROCEDURESCHEMA" ]]; then
	GLOBALS+=("--use-procedure-schema=$USEPROCEDURESCHEMA")
fi
if [[ -n "$VALIDATEXMLCHANGELOGFILES" ]]; then
	GLOBALS+=("--validate-xml-changelog-files=$VALIDATEXMLCHANGELOGFILES")
fi

docker-entrypoint.sh "${GLOBALS[@]}" diff-changelog "${PARAMS[@]}"
